trigger:
  - development

parameters:
  - name: environment
    displayName: Which machine you want to deploy?
    type: string
    default: 'SFORDS-144'
    values:
      - SFORDS-142
      - SFORDS-144

variables:
  ${{ if eq(parameters['environment'], 'SFORDS-142') }}:
    k8sServiceEndpoint: 'KubernetesService-SFORDS-142'
    AGENT: 'SFORDS-142'
  ${{ if eq(parameters['environment'], 'SFORDS-144') }}:
    k8sServiceEndpoint: 'KubernetesService-SFORDS-144'
    AGENT: 'SFORDS-144'

pool:
  name: BlueHydrogen
  demands:
    - Agent.Name -equals $(AGENT)

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install package sonar:sonar'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'



- task: Docker@2
  inputs:
    containerRegistry: 'BlueHydrogenDocker'
    repository: 'bluehydrogen/pm-simulator-kafka'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Kubernetes Service Connection'
#     kubernetesServiceEndpoint: 'Azure Cloud BlueHydrogen K8s'
#     command: 'apply'
#     useConfigurationFile: true
#     configuration: 'Deployment/Deployment.yaml'
#     secretType: 'dockerRegistry'
#     containerRegistryType: 'Azure Container Registry'